# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_pics/%Y-%m-%d/', verbose_name='Student picture'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_pics/%Y-%m-%d/', verbose_name='Teacher picture'),
        ),
    ]
