# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20151224_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='requirement',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='achievement',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
