# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 13:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0004_auto_20151231_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='student',
        ),
        migrations.RemoveField(
            model_name='order',
            name='teacher',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(default=1520000000),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, '\u8ba2\u5355\u751f\u6210'), (1, '\u5b66\u751f\u5df2\u4ed8\u6b3e'), (2, '\u8001\u5e08\u5df2\u786e\u8ba4'), (3, '\u5b66\u751f\u5df2\u8bc4\u4ef7'), (4, '\u5df2\u5b8c\u6210')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='student_name',
            field=models.CharField(default='John Doe', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='subjects',
            field=models.ManyToManyField(to='education.Subject'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.IntegerField(choices=[(1, '\u4e0a\u5348'), (2, '\u4e0b\u5348'), (3, '\u665a\u4e0a')], default=3),
        ),
        migrations.AddField(
            model_name='order',
            name='user_student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
