# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_teacher_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
