# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_teacher_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rate_num',
            field=models.IntegerField(default=0),
        ),
    ]
