# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_teacher_rate_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50)),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rate_num',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Rating'),
        ),
    ]
