# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_auto_20151226_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.Teacher'),
            preserve_default=False,
        ),
    ]
