# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='problem_pics/%Y-%m-%d/', verbose_name='Problem picture'),
        ),
    ]
