# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_city_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='available',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
